export const en: Record<string, any> = {
  nav: { home: 'Home', curriculum: 'Curriculum', qna: 'Q&A', articles: 'Articles', login: 'Login', search: 'Search' },
  hero: { tagline: 'Based on Quran and Hadith', title: 'Learning Islam for Kids', titleHighlight: 'Made Easy to Understand', subtitle: 'Find answers based on Shariah, simple analogies, and authentic dalil in seconds.', searchPlaceholder: 'Search: Why do we pray?', searchButton: 'Find Answers', filterLabel: 'Quick Filter:' },
  curriculum: { title: 'Main Curriculum', subtitle: 'Structured Islamic learning modules.', exploreAll: 'Explore All', startLearning: 'Start Learning' },
  donation: { title: 'Support Adably', methods: 'Donation Methods', verified: 'Verified Donors', confirmTitle: 'Confirm Donation', name: 'Name', amount: 'Amount (IDR)', method: 'Method', message: 'Message (optional)', proof: 'Transfer Proof', proofHint: 'Click to upload image', submit: 'Submit Donation Confirmation', thanks: 'Jazaakumullaahu khairan 🤲' },
  feedback: { badge: 'Feedback', title: 'Help Us Improve', subtitle: 'Your feedback is invaluable for Adably\'s development.', name: 'Name', email: 'Email (optional)', type: 'Type', kritik: 'Criticism', saran: 'Suggestion', pertanyaan: 'Question', messagePlaceholder: 'Write your feedback here...', submit: 'Send Feedback' },
  admin: { dashboard: 'Dashboard', writeContent: 'Write Content', myContent: 'My Content', inbox: 'Inbox', review: 'Content Review', structure: 'Manage Structure', donationInbox: 'Donation Inbox', feedback: 'Feedback', users: 'User Management', donationSettings: 'Donation Settings', settings: 'Settings', messages: 'Messages', rewards: 'Point Rewards', withdrawals: 'Withdrawals', profile: 'Profile', publicPage: 'Public Page', logout: 'Logout', hello: 'Hello', welcome: 'Welcome back to the control panel.', markAllRead: 'Mark All Read', noNotifications: 'No notifications yet.', loading: 'Loading...', verify: 'Verify', verified: 'Verified', pending: 'Pending', list: 'List', report: 'Report', totalVerified: 'Total Verified Donations', totalDonors: 'Total Donors', perMonth: 'Per Month', noFeedback: 'No feedback yet.', noDonation: 'No donations yet.', export: 'Export Data', import: 'Import Data', backup: 'Database Backup', auditLog: 'Audit Log', exportCSV: 'Export CSV' },
  rewards: { balance: 'Point Balance', equivalent: 'equivalent to', history: 'Point History', withdraw: 'Withdraw', withdrawTitle: 'Withdrawal Request', amount: 'Point Amount', minPoints: 'Minimum', bankInfo: 'Bank Info', bankName: 'Bank Name', bankAccount: 'Account Number', bankHolder: 'Account Holder', submitWithdraw: 'Submit Withdrawal', leaderboard: 'Author Leaderboard', processWithdraw: 'Process Withdrawal', approve: 'Approve', reject: 'Reject', disburse: 'Disbursed' },
  profile: { title: 'My Profile', personalInfo: 'Personal Information', bankInfo: 'Bank Information', changePassword: 'Change Password', save: 'Save', name: 'Name', phone: 'Phone Number', bio: 'Bio', language: 'Language' },
  common: { save: 'Save', cancel: 'Cancel', delete: 'Delete', edit: 'Edit', close: 'Close', confirm: 'Confirm', yes: 'Yes', no: 'No', success: 'Success', error: 'Error', viewProof: 'View Proof', markRead: 'Mark Read', send: 'Send', attach: 'Attach', newChat: 'New Chat', noMessages: 'No messages yet.', typeMessage: 'Type a message...', translateHint: 'This content is in Bahasa Indonesia', translateButton: 'Translate via Google' },
  footer: { tagline: 'Islamic education platform for children — based on Quran and Hadith.', rights: 'Copyright' },
};
