export const id: Record<string, any> = {
  nav: { home: 'Beranda', curriculum: 'Kurikulum', qna: 'Tanya Jawab', articles: 'Artikel', login: 'Masuk', search: 'Cari' },
  hero: { tagline: 'Sesuai Alquran dan Hadist', title: 'Belajar Islam Anak dengan', titleHighlight: 'Cara yang Mudah Dipahami', subtitle: 'Temukan jawaban syar\'i, analogi sederhana, dan dalil shahih dalam hitungan detik.', searchPlaceholder: 'Cari: Kenapa kita shalat?', searchButton: 'Cari Jawaban', filterLabel: 'Filter Cepat:' },
  curriculum: { title: 'Kurikulum Utama', subtitle: 'Modul materi dasar keislaman yang terstruktur.', exploreAll: 'Jelajahi Semua', startLearning: 'Mulai Belajar' },
  donation: { title: 'Dukung Adably', methods: 'Metode Donasi', verified: 'Donatur Terverifikasi', confirmTitle: 'Konfirmasi Donasi', name: 'Nama', amount: 'Jumlah (Rp)', method: 'Metode', message: 'Pesan (opsional)', proof: 'Bukti Transfer', proofHint: 'Klik untuk upload gambar', submit: 'Kirim Konfirmasi Donasi', thanks: 'Jazaakumullaahu khairan 🤲' },
  feedback: { badge: 'Kritik & Saran', title: 'Bantu Kami Lebih Baik', subtitle: 'Masukan Anda sangat berharga untuk pengembangan Adably.', name: 'Nama', email: 'Email (opsional)', type: 'Jenis', kritik: 'Kritik', saran: 'Saran', pertanyaan: 'Pertanyaan', messagePlaceholder: 'Tulis masukan Anda di sini...', submit: 'Kirim Masukan' },
  admin: { dashboard: 'Dashboard', writeContent: 'Tulis Konten', myContent: 'Konten Saya', inbox: 'Inbox', review: 'Review Konten', structure: 'Kelola Struktur', donationInbox: 'Donasi Masuk', feedback: 'Kritik & Saran', users: 'Manajemen User', donationSettings: 'Donasi Settings', settings: 'Pengaturan', messages: 'Pesan', rewards: 'Reward Poin', withdrawals: 'Withdrawal', profile: 'Profil', publicPage: 'Halaman Publik', logout: 'Keluar Akses', hello: 'Halo', welcome: 'Selamat datang kembali di panel kontrol.', markAllRead: 'Tandai Semua Dibaca', noNotifications: 'Belum ada notifikasi.', loading: 'Memuat...', verify: 'Verifikasi', verified: 'Terverifikasi', pending: 'Menunggu', list: 'Daftar', report: 'Laporan', totalVerified: 'Total Donasi Terverifikasi', totalDonors: 'Jumlah Donatur', perMonth: 'Per Bulan', noFeedback: 'Belum ada feedback.', noDonation: 'Belum ada donasi masuk.', export: 'Export Data', import: 'Import Data', backup: 'Backup Database', auditLog: 'Audit Log', exportCSV: 'Export CSV' },
  rewards: { balance: 'Saldo Poin', equivalent: 'setara', history: 'Riwayat Poin', withdraw: 'Tarik Reward', withdrawTitle: 'Permintaan Withdrawal', amount: 'Jumlah Poin', minPoints: 'Minimal', bankInfo: 'Data Rekening', bankName: 'Nama Bank', bankAccount: 'Nomor Rekening', bankHolder: 'Nama Pemilik', submitWithdraw: 'Ajukan Withdrawal', leaderboard: 'Leaderboard Author', processWithdraw: 'Proses Withdrawal', approve: 'Setujui', reject: 'Tolak', disburse: 'Sudah Transfer' },
  profile: { title: 'Profil Saya', personalInfo: 'Informasi Pribadi', bankInfo: 'Informasi Rekening', changePassword: 'Ubah Password', save: 'Simpan', name: 'Nama', phone: 'Nomor HP', bio: 'Bio', language: 'Bahasa' },
  common: { save: 'Simpan', cancel: 'Batal', delete: 'Hapus', edit: 'Edit', close: 'Tutup', confirm: 'Konfirmasi', yes: 'Ya', no: 'Tidak', success: 'Berhasil', error: 'Gagal', viewProof: 'Lihat Bukti', markRead: 'Tandai Dibaca', send: 'Kirim', attach: 'Lampirkan', newChat: 'Chat Baru', noMessages: 'Belum ada pesan.', typeMessage: 'Ketik pesan...', translateHint: 'Konten ini dalam Bahasa Indonesia', translateButton: 'Terjemahkan via Google' },
  footer: { tagline: 'Platform edukasi Islam untuk anak — sesuai Alquran dan Hadist.', rights: 'Hak Cipta' },
};
